"""Paper-1 composition over injected platform APIs and the SEM method package."""

from .logging import bind_project_logging
from .minecraft_evidence import (
    MinecraftEvidenceAdapter,
    MinecraftEvidenceAdmissionError,
    MinecraftObservationView,
    SEMMinecraftEvidenceIngestor,
)
from .minecraft_workload import (
    MinecraftEnvironmentActionResult,
    MinecraftEnvironmentObservation,
    MinecraftPlannerDecision,
    MinecraftSuccessSpec,
    MinecraftTaskRunResult,
    MinecraftTaskSpec,
    MinecraftCognitionFactoryPort,
    MinecraftCognitionRunnerPort,
    MinecraftWorkloadFailure,
    MinecraftWorkloadRunner,
    ScriptedMinecraftPlanner,
    evaluate_success,
    task_from_mapping,
    validate_task_manifest,
)
from .method import build_fixed_memory_treatment, build_self_evolving_treatment
from .candidate_method import (
    CandidateMethodMaterializationError,
    CandidateMethodMaterializerPort,
    SemPaperCandidateMethodMaterializer,
    build_seed_candidate,
    build_seed_x_candidate,
)
from .closed_world_reference import (
    ClosedWorldGoal,
    ReferenceClosedWorldCompletion,
    ReferenceClosedWorldDynamics,
    ReferenceClosedWorldPlanner,
    ReferenceClosedWorldPlannerFactory,
    ReferenceClosedWorldState,
    SEMClosedWorldEvidence,
    SEMClosedWorldEvidenceFactory,
    reference_closed_world_spec,
)
from .project import (
    SemPaperBindings,
    SemPaperCompositionPorts,
    SemPaperProjectComposition,
    compose_sem_paper,
)
from .minecraft_branch import (
    MinecraftBranchExecutionError,
    MinecraftBranchExecutionResult,
    MinecraftBranchExecutorPort,
    MinecraftPairedBranchRunner,
)
from .minecraft_runtime_adapter import (
    MinecraftWorkloadEnvironmentAdapter,
    MinecraftWorkloadEnvironmentAdapterError,
)
from .minecraft_workload_executor import (
    MinecraftWorkloadBatchResult,
    MinecraftWorkloadBindingCloseError,
    MinecraftWorkloadBindingFactoryPort,
    MinecraftWorkloadBindingPort,
    MinecraftWorkloadBranchExecutor,
)
from .minecraft_binding import (
    SemPaperBranchRuntimeRequestFactoryPort,
    SemPaperMethodObservationSinkFactoryPort,
    SemPaperMinecraftWorkloadBinding,
    SemPaperMinecraftWorkloadBindingFactory,
    SemPaperPlannerFactoryPort,
    SemPaperWorkloadBindingError,
)
from .minecraft_production import (
    SemPaperMinecraftProductionRoot,
    compose_sem_paper_minecraft_production_root,
)
from .non_minecraft_workload import (
    NonMinecraftEnvironmentFactoryPort,
    NonMinecraftEvidenceFactoryPort,
    NonMinecraftEvidencePort,
    NonMinecraftMethodObservationSinkFactoryPort,
    NonMinecraftPlannerFactoryPort,
    NonMinecraftResultSinkPort,
    NonMinecraftStatePort,
    NonMinecraftWorkloadCloseError,
    NonMinecraftWorkloadOpenError,
    SemPaperNonMinecraftProductionRoot,
    SemPaperNonMinecraftStudyUnitAdapter,
    SemPaperNonMinecraftWorkloadBinding,
    SemPaperNonMinecraftWorkloadBindingFactory,
    SemPaperNonMinecraftWorkloadPorts,
    compose_sem_paper_non_minecraft_production_root,
    execute_sem_paper_non_minecraft_workload,
)
from .study_execution import (
    MinecraftSourceCutPublicationPort,
    SemPaperMinecraftStudyUnitAdapter,
    SemPaperStudyUnitError,
)
from .model_planner import (
    SemPaperModelPlanner,
    SemPaperModelPlannerBinding,
    SemPaperModelPlannerError,
    SemPaperModelPlannerFactory,
)
from .minecraft_agent import (
    SemPaperCognitionEvidenceAdapter,
    SemPaperCognitionPlannerAdapter,
    SemPaperCognitionProgressAdapter,
)
from .minecraft_host import SemPaperMinecraftBranchRequestFactory, SemPaperMinecraftHostInputs
from .study import (
    SEM_PAPER_METRIC_NAMES,
    build_sem_paper_study_protocol,
    compile_sem_paper_experiment_plan,
)
from .scope import register_sem_paper_scope

__all__ = [
    "SemPaperBindings",
    "SemPaperCompositionPorts",
    "SemPaperProjectComposition",
    "bind_project_logging",
    "MinecraftEvidenceAdapter",
    "MinecraftEvidenceAdmissionError",
    "MinecraftObservationView",
    "SEMMinecraftEvidenceIngestor",
    "MinecraftEnvironmentActionResult",
    "MinecraftEnvironmentObservation",
    "MinecraftPlannerDecision",
    "MinecraftSuccessSpec",
    "MinecraftTaskRunResult",
    "MinecraftTaskSpec",
    "MinecraftCognitionFactoryPort",
    "MinecraftCognitionRunnerPort",
    "MinecraftWorkloadFailure",
    "MinecraftWorkloadRunner",
    "ScriptedMinecraftPlanner",
    "evaluate_success",
    "task_from_mapping",
    "validate_task_manifest",
    "build_fixed_memory_treatment",
    "build_self_evolving_treatment",
    "CandidateMethodMaterializationError",
    "ClosedWorldGoal",
    "CandidateMethodMaterializerPort",
    "SemPaperCandidateMethodMaterializer",
    "ReferenceClosedWorldCompletion",
    "ReferenceClosedWorldDynamics",
    "ReferenceClosedWorldPlanner",
    "ReferenceClosedWorldPlannerFactory",
    "ReferenceClosedWorldState",
    "SEMClosedWorldEvidence",
    "SEMClosedWorldEvidenceFactory",
    "reference_closed_world_spec",
    "build_seed_x_candidate",
    "build_seed_candidate",
    "compose_sem_paper",
    "MinecraftBranchExecutionError",
    "MinecraftBranchExecutionResult",
    "MinecraftBranchExecutorPort",
    "MinecraftPairedBranchRunner",
    "MinecraftWorkloadEnvironmentAdapter",
    "MinecraftWorkloadEnvironmentAdapterError",
    "MinecraftWorkloadBatchResult",
    "MinecraftWorkloadBindingCloseError",
    "MinecraftWorkloadBindingFactoryPort",
    "MinecraftWorkloadBindingPort",
    "MinecraftWorkloadBranchExecutor",
    "SemPaperBranchRuntimeRequestFactoryPort",
    "SemPaperMethodObservationSinkFactoryPort",
    "SemPaperMinecraftWorkloadBinding",
    "SemPaperMinecraftWorkloadBindingFactory",
    "SemPaperPlannerFactoryPort",
    "SemPaperWorkloadBindingError",
    "SemPaperMinecraftProductionRoot",
    "compose_sem_paper_minecraft_production_root",
    "NonMinecraftEnvironmentFactoryPort",
    "NonMinecraftEvidenceFactoryPort",
    "NonMinecraftEvidencePort",
    "NonMinecraftMethodObservationSinkFactoryPort",
    "NonMinecraftPlannerFactoryPort",
    "NonMinecraftResultSinkPort",
    "NonMinecraftStatePort",
    "NonMinecraftWorkloadCloseError",
    "NonMinecraftWorkloadOpenError",
    "SemPaperNonMinecraftProductionRoot",
    "SemPaperNonMinecraftStudyUnitAdapter",
    "SemPaperNonMinecraftWorkloadBinding",
    "SemPaperNonMinecraftWorkloadBindingFactory",
    "SemPaperNonMinecraftWorkloadPorts",
    "compose_sem_paper_non_minecraft_production_root",
    "execute_sem_paper_non_minecraft_workload",
    "SemPaperMinecraftStudyUnitAdapter",
    "MinecraftSourceCutPublicationPort",
    "SemPaperStudyUnitError",
    "SemPaperModelPlanner",
    "SemPaperModelPlannerBinding",
    "SemPaperModelPlannerError",
    "SemPaperModelPlannerFactory",
    "SemPaperCognitionEvidenceAdapter",
    "SemPaperCognitionPlannerAdapter",
    "SemPaperCognitionProgressAdapter",
    "SemPaperMinecraftBranchRequestFactory",
    "SemPaperMinecraftHostInputs",
    "SEM_PAPER_METRIC_NAMES",
    "build_sem_paper_study_protocol",
    "compile_sem_paper_experiment_plan",
    "register_sem_paper_scope",
]
