from __future__ import annotations

from typing import Protocol

from .contracts import ResourceIdentity, ResourceLease, ResourceOwner


class ResourceOwnershipPort(Protocol):
    def register_owner(self, owner: ResourceOwner) -> None: ...
    def owner(self, resource: ResourceIdentity) -> ResourceOwner: ...
    def remove_owner(self, resource: ResourceIdentity) -> None: ...


class ResourceLeasePort(Protocol):
    def acquire(self, lease: ResourceLease) -> None: ...
    def release(self, lease_id: str) -> ResourceLease: ...
    def get(self, lease_id: str) -> ResourceLease: ...
    def active_for(self, resource: ResourceIdentity) -> tuple[ResourceLease, ...]: ...


__all__ = ["ResourceLeasePort", "ResourceOwnershipPort"]
