from __future__ import annotations

from .source_authority_contracts import SourceAuthorityRule
from .source_authority_matchers import exact_call, suffix_call


DEFAULT_SOURCE_AUTHORITY_RULES: tuple[_AuthorityRule, ...] = (
    SourceAuthorityRule(
        "filesystem.atomic_replace",
        "os.replace",
        (
            "research_platform.platform.kernel.durability.durable_file",
            "research_platform.model.request.prompt.runtime.atomic_publication",
        ),
        exact_call("os.replace"),
    ),
    SourceAuthorityRule(
        "process.async_command_spawn",
        "asyncio.create_subprocess_exec",
        ("research_platform.runtime.process.supervision.runtime.command_runner",),
        exact_call("asyncio.create_subprocess_exec"),
    ),
    SourceAuthorityRule(
        "service.process_spawn",
        "subprocess.Popen",
        ("research_platform.runtime.service.runtime.linux_spawn",),
        exact_call("subprocess.Popen"),
    ),
    SourceAuthorityRule(
        "process.process_group_signal",
        "os.killpg",
        (
            "research_platform.runtime.process.supervision.runtime.command_runner",
            "research_platform.runtime.service.runtime.linux_signal",
        ),
        exact_call("os.killpg"),
    ),
    SourceAuthorityRule(
        "environment.external_action",
        "_environment_session.act",
        ("research_platform.execution.workflow.implementations.context_action.action_effect_provider",),
        suffix_call("_environment_session.act"),
    ),
    SourceAuthorityRule(
        "environment.prepared_external_action",
        "_environment_session.execute_prepared_action",
        ("research_platform.execution.workflow.implementations.context_action.action_effect_provider",),
        suffix_call("_environment_session.execute_prepared_action"),
    ),
    SourceAuthorityRule(
        "environment.effect_reconcile",
        "_environment_session.reconcile",
        ("research_platform.execution.workflow.implementations.context_action.action_effect_provider",),
        suffix_call("_environment_session.reconcile"),
    ),
    SourceAuthorityRule(
        "environment.action_recovery_prepare",
        "_environment_session.prepare_action_recovery",
        ("research_platform.execution.workflow.implementations.context_action.action_authorization",),
        suffix_call("_environment_session.prepare_action_recovery"),
    ),
    SourceAuthorityRule(
        "environment.action_recovery_reconcile",
        "_environment_session.reconcile_prepared_action",
        ("research_platform.execution.workflow.implementations.context_action.action_effect_provider",),
        suffix_call("_environment_session.reconcile_prepared_action"),
    ),
    SourceAuthorityRule(
        "participant.checkpoint_capture",
        "adapter.checkpoint",
        ("research_platform.participant.session.runtime.checkpoint_runtime",),
        suffix_call("adapter.checkpoint"),
    ),
    SourceAuthorityRule(
        "participant.checkpoint_restore",
        "adapter.restore",
        ("research_platform.participant.session.runtime.checkpoint_runtime",),
        suffix_call("adapter.restore"),
    ),
    SourceAuthorityRule(
        "study.checkpoint_publish",
        "store.publish",
        ("research_platform.experimentation.checkpoint.runtime.capture",),
        suffix_call("store.publish", "_store.publish"),
    ),
    SourceAuthorityRule(
        "effect_journal.prepare",
        "_effect_journal.prepare",
        ("research_platform.execution.workflow.runtime.effect_intents",),
        suffix_call("_effect_journal.prepare"),
    ),
    SourceAuthorityRule(
        "effect_journal.record_result",
        "_effect_journal.record_result",
        ("research_platform.execution.workflow.runtime.effect_intents",),
        suffix_call("_effect_journal.record_result"),
    ),
    SourceAuthorityRule(
        "effect_journal.record_reconciled",
        "_effect_journal.record_reconciled",
        ("research_platform.execution.workflow.runtime.effect_intents",),
        suffix_call("_effect_journal.record_reconciled"),
    ),
    SourceAuthorityRule(
        "effect_journal.record_consumed",
        "_effect_journal.record_consumed",
        ("research_platform.execution.workflow.runtime.effect_intents",),
        suffix_call("_effect_journal.record_consumed"),
    ),
    SourceAuthorityRule(
        "effect_journal.record_not_applied",
        "_effect_journal.record_not_applied",
        ("research_platform.execution.workflow.runtime.effect_intents",),
        suffix_call("_effect_journal.record_not_applied"),
    ),
    SourceAuthorityRule(
        "effect_journal.pending_scope_read",
        "_effect_journal.unresolved_for_scope",
        ("research_platform.execution.workflow.runtime.effect_intents",),
        suffix_call("_effect_journal.unresolved_for_scope"),
    ),
    SourceAuthorityRule(
        "capability.effect_prepare",
        "prepare_capability_effect",
        ("research_platform.execution.workflow.implementations.agent_turn.capability_effect_provider",),
        suffix_call("prepare_capability_effect"),
    ),
    SourceAuthorityRule(
        "capability.effect_execute",
        "execute_prepared_capability",
        ("research_platform.execution.workflow.implementations.agent_turn.capability_effect_provider",),
        suffix_call("execute_prepared_capability"),
    ),
    SourceAuthorityRule(
        "capability.effect_reconcile",
        "reconcile_prepared_capability",
        ("research_platform.execution.workflow.implementations.agent_turn.capability_effect_provider",),
        suffix_call("reconcile_prepared_capability"),
    ),

)

__all__ = ["DEFAULT_SOURCE_AUTHORITY_RULES"]
